[workspace]
default-members = ["leftwm", "leftwm-core", "display-servers/xlib-display-server", "display-servers/smithay-display-server"]
members = ["leftwm", "leftwm-core", "display-servers/xlib-display-server", "display-servers/smithay-display-server"]

[profile.optimized]
inherits = "release"
codegen-units = 1
strip = "symbols"
lto = "fat"
